name: Run Cypress Tests on Folder Changes

on:
  push:
    branches: [master]
    paths:
      - 'cypress/**'
      - 'cypress/e2e/**'
      - 'cypress/e2e/Project_BigFish/**'
      - 'package.json'
      - 'package-lock.json'

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.16.0'

    - name: Install Dependencies
      run: |
        npm install
        npm install cypress --save-dev

    - name: Run Cypress Tests
      run: npx cypress run --spec "cypress/e2e/Project_BigFish/UI_Playground/PageObjecModel/Tests/homepage_link_Test.cy.js", "cypress/e2e/Project_BigFish/UI_Playground/PageObjecModel/Tests/dynamicID_Test.cy.js"
