name: Project Eagle Eye

on:
  push:
    branches: [master]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.16.0'

    - name: Install Dependencies
      run: |
        npm install
        npm install cypress --save-dev

    - name: Run Cypress Tests
      run: npx cypress run --spec "cypress/e2e/Project_EagleEye/PageObjectModel/loginTest.cy.js, cypress/e2e/Project_EagleEye/PageObjectModel/forgotPasswordTest.cy.js"
