name: Run Cypress Tests
on:

  push:
    branches: [ master ]

jobs:
  run-tests:
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
     
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.16.0'
     
      - name: Install Dependencies
        run: npm install

      - name: Cache Cypress binary
        uses: actions/cache@v2
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('**/package-lock.json') }}

      - name: Run Cypress tests
        uses: cypress/included@10.3.0
        with:
         working-directory: ./cypress
         start: npm run cy:run -- --spec "cypress/integration/**/*homepage_link_Test.spec.js"
